/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package agro_shop_management;

import java.awt.HeadlessException;
import java.awt.Toolkit;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */

public class LoginPage extends javax.swing.JFrame {

    /**
     * Creates new form LoginPage
     */
    public LoginPage() {
        // below two line are use for the  decoration and resizability of this page
        this.setUndecorated(false);
        this.setResizable(true);
        
        initComponents();
        seticon(); // it is use for set icon of this page
        //below coding use for set size of this page according the resolution of a screen
        Toolkit tk = Toolkit.getDefaultToolkit();
        int x = (int) tk.getScreenSize().getWidth();
        int y = (int) tk.getScreenSize().getHeight();
        this.setSize(x,y);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jPanel1 = new javax.swing.JPanel();
        UserNameLabel = new javax.swing.JLabel();
        passLabell = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        UserName = new javax.swing.JTextField();
        Password = new javax.swing.JPasswordField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        forget_button = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        SignIn = new javax.swing.JButton();
        pannel_icon_label = new javax.swing.JLabel();
        Header_of_shop = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 255, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 0, 51)), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 3, 36), new java.awt.Color(204, 0, 51))); // NOI18N
        jPanel1.setLayout(null);

        UserNameLabel.setBackground(new java.awt.Color(0, 204, 204));
        UserNameLabel.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        UserNameLabel.setForeground(new java.awt.Color(51, 0, 102));
        UserNameLabel.setText("User Name");
        UserNameLabel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(UserNameLabel);
        UserNameLabel.setBounds(100, 170, 100, 31);

        passLabell.setBackground(new java.awt.Color(0, 255, 153));
        passLabell.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        passLabell.setForeground(new java.awt.Color(0, 51, 102));
        passLabell.setText("Password");
        passLabell.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(passLabell);
        passLabell.setBounds(100, 240, 100, 30);

        jLabel4.setBackground(new java.awt.Color(51, 255, 51));
        jLabel4.setForeground(new java.awt.Color(51, 255, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/agro_shop_management/13.png"))); // NOI18N
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel4.setName(""); // NOI18N
        jLabel4.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jPanel1.add(jLabel4);
        jLabel4.setBounds(210, 0, 150, 120);

        UserName.setBackground(new java.awt.Color(153, 255, 255));
        UserName.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        UserName.setForeground(new java.awt.Color(51, 0, 102));
        UserName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        UserName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 51)));
        UserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserNameActionPerformed(evt);
            }
        });
        jPanel1.add(UserName);
        UserName.setBounds(240, 180, 180, 31);

        Password.setBackground(new java.awt.Color(153, 255, 255));
        Password.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Password.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Password.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 102)));
        Password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordActionPerformed(evt);
            }
        });
        jPanel1.add(Password);
        Password.setBounds(240, 250, 180, 30);
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(240, 220, 170, 10);
        jPanel1.add(jSeparator2);
        jSeparator2.setBounds(240, 290, 178, 10);

        forget_button.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        forget_button.setForeground(new java.awt.Color(51, 0, 51));
        forget_button.setText("Forget password / registration");
        forget_button.setBorder(null);
        forget_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                forget_buttonActionPerformed(evt);
            }
        });
        jPanel1.add(forget_button);
        forget_button.setBounds(150, 390, 220, 20);

        clear.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        clear.setForeground(new java.awt.Color(255, 51, 102));
        clear.setText("Clear");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        jPanel1.add(clear);
        clear.setBounds(320, 330, 73, 31);

        SignIn.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        SignIn.setForeground(new java.awt.Color(255, 51, 102));
        SignIn.setText("Login");
        SignIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignInActionPerformed(evt);
            }
        });
        jPanel1.add(SignIn);
        SignIn.setBounds(110, 330, 77, 31);

        pannel_icon_label.setBackground(new java.awt.Color(204, 255, 204));
        pannel_icon_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/agro_shop_management/pannel3.jpg"))); // NOI18N
        pannel_icon_label.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 51, 51)));
        jPanel1.add(pannel_icon_label);
        pannel_icon_label.setBounds(0, 0, 600, 440);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(210, 140, 580, 430);

        Header_of_shop.setFont(new java.awt.Font("Times New Roman", 3, 48)); // NOI18N
        Header_of_shop.setForeground(new java.awt.Color(204, 0, 102));
        Header_of_shop.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Header_of_shop.setText("Agro Shop Management System");
        getContentPane().add(Header_of_shop);
        Header_of_shop.setBounds(280, 10, 740, 80);

        jLabel6.setBackground(new java.awt.Color(0, 0, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/agro_shop_management/a15.jpg"))); // NOI18N
        jLabel6.setName(""); // NOI18N
        jLabel6.setPreferredSize(new java.awt.Dimension(1000, 600));
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 100, 1370, 580);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordActionPerformed

    private void UserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserNameActionPerformed

    private void forget_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forget_buttonActionPerformed
        // TODO add your handling code here:
        Forget_pass f = new Forget_pass();
        f.setVisible(true);
       // f.dispose();
      // LoginPage p = new LoginPage();
       //p.setVisible(true);
       
        
    }//GEN-LAST:event_forget_buttonActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // TODO add your handling code here:
        UserName.setText("");
        Password.setText("");
    }//GEN-LAST:event_clearActionPerformed

    private void SignInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignInActionPerformed
        // TODO add your handling code here:
        // this method use for to perform the login funcitonality
       final String user = UserName.getText().trim();
       final String pass = Password.getText().trim();
       // below line use for validation of project
       if(!user.matches("^[a-zA-Z\\\\s]*$")){    // regular expression are use for validation
         JOptionPane.showMessageDialog(null, " user Name contain only alphabets");
           return;
        }
           
        try {
            Agro_Shop_Management  obj1 = new Agro_Shop_Management(); // this obj created for jdbc connection
            obj1.Connection();
            String query = "select UserName, Password, userType from UserDetails where UserName = ? or Password = ?";
            obj1.ps = obj1.con.prepareStatement(query);
            obj1.ps.setString(1,user);
            obj1.ps.setString(2, pass);
            ResultSet rs = obj1.ps.executeQuery();
           // System.out.println("Query done");
            
            if(rs.next()){
                HomePage h = new HomePage();
                Agro_Shop_Management.userType = rs.getString("userType");//to identify the type of logged in user
                        //System.out.println("user = "+Agro_Shop_Management.userType);
                h.setVisible(true);
                this.dispose(); 
            } else
                JOptionPane.showMessageDialog(null,"incorrect userName or Password");
            obj1.st.close();
            obj1.con.close();
            obj1.ps.close();
            obj1=null;
        } catch(SQLException | HeadlessException e){
           // System.out.println("Exception 2: "+e);
            JOptionPane.showMessageDialog(null,"Exception in program plz contact developer");
        }
    }
        public static void main(String args[]) {
     
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginPage().setVisible(true);
            }
        });
    }//GEN-LAST:event_SignInActionPerformed


    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Header_of_shop;
    private javax.swing.JPasswordField Password;
    private javax.swing.JButton SignIn;
    private javax.swing.JTextField UserName;
    private javax.swing.JLabel UserNameLabel;
    private javax.swing.JButton clear;
    private javax.swing.JButton forget_button;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel pannel_icon_label;
    private javax.swing.JLabel passLabell;
    // End of variables declaration//GEN-END:variables

    private void seticon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("IconImage.jpg")));
    }
}
