/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package agro_shop_management;

import java.awt.print.PrinterException;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class PrintBill extends javax.swing.JFrame {

    /**
     * Creates new form PrintBill
     */
    int billLocal ;
    String C_name;
    String mo;
    String product_n;
    String pId;
    String BId;
    String Q;
    String R;
    float Total_Amount;
    String c_date;
    public PrintBill() {
        this.setResizable(false);
        initComponents();
    }

    /**
     *
     * @param billNo
     * @param name
     * @param mobile
     */
    void dataFromHome(int billNo,String name, String mobile ) {
         this.billLocal = billNo;
         this.C_name = name;
         this.mo = mobile;
    
    }
    void Product(String p_name, String p_id, String B_id, String Quantity, String Rate, float Total, String date){
            this.product_n = p_name;
            this.pId = p_id;
            this.BId = B_id;
            this.Q = Quantity;
            this.R = Rate;
            this.Total_Amount = Total;
            this.c_date = date;
           GenerateBill(); 
    } 
    void GenerateBill(){
        BillArea.setText("***************  Shree krushi Kendra ************\n");
        BillArea.setText(BillArea.getText()+"           Burhanpur, Dist. Burhanpur(M.P)450331      \n\n");
        BillArea.setText(BillArea.getText()+"Bill No : "+billLocal+"                                                                     Date: " +c_date+"\n");
        BillArea.setText( BillArea.getText()+"Customer Name : "+C_name+" \n"+"Mobile : "+mo+"\n\n");
        BillArea.setText( BillArea.getText()+"============================================================\n");
        BillArea.setText( BillArea.getText()+"Product Names :  "+product_n+"\n");
        BillArea.setText( BillArea.getText()+"Product Id    :  "+pId+"\n");
        BillArea.setText( BillArea.getText()+"Batch no      :  "+BId+"\n");
        BillArea.setText( BillArea.getText()+"Quantities    :  "+Q+"\n");
        BillArea.setText( BillArea.getText()+"Rates         :  "+R+"\n");
        BillArea.setText( BillArea.getText()+"TotalAmount   :  "+Total_Amount+"\ttax included\n");
        BillArea.setText( BillArea.getText()+"\nSignature of shopOwner                           Signature Of customer\n");
      
    
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        BillArea = new javax.swing.JTextArea();
        PrintBillFormate = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        BillArea.setColumns(20);
        BillArea.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        BillArea.setRows(5);
        jScrollPane1.setViewportView(BillArea);

        PrintBillFormate.setBackground(new java.awt.Color(153, 153, 255));
        PrintBillFormate.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        PrintBillFormate.setForeground(new java.awt.Color(204, 0, 0));
        PrintBillFormate.setText("PrintBill");
        PrintBillFormate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrintBillFormateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(222, 222, 222)
                .addComponent(PrintBillFormate)
                .addContainerGap(265, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(PrintBillFormate)
                .addGap(0, 32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PrintBillFormateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrintBillFormateActionPerformed
        // TODO add your handling code here:
        try {
            BillArea.print();
        } catch (PrinterException ex) {
            JOptionPane.showMessageDialog(null,"Exception plz contact Developer \n"+ex);
        }
    }//GEN-LAST:event_PrintBillFormateActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea BillArea;
    private javax.swing.JButton PrintBillFormate;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
