/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package agro_shop_management;

import java.awt.HeadlessException;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class SellDetailsPage extends javax.swing.JFrame {

    /**
     * Creates new form SellDetailsPage
     */
    public SellDetailsPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ShowData = new javax.swing.JTable();
        showRecords = new javax.swing.JButton();
        CheckTotalAmount = new javax.swing.JTextField();
        CheckTotalButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        TakeDate = new javax.swing.JTextField();
        DateSellAmount = new javax.swing.JTextField();
        CheckAmountOndate = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 153, 153));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Sells Details");
        jLabel1.setToolTipText("");

        ShowData.setBackground(new java.awt.Color(0, 153, 153));
        ShowData.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        ShowData.setForeground(new java.awt.Color(204, 204, 204));
        ShowData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Bill No", "Customer name", "Date(MM/DD/YYYY)", "TotalAmount"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ShowData.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ShowData.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                ShowDataAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane1.setViewportView(ShowData);

        showRecords.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        showRecords.setForeground(new java.awt.Color(204, 0, 51));
        showRecords.setText("Show all Records");
        showRecords.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showRecordsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 686, Short.MAX_VALUE)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(238, 238, 238)
                .addComponent(showRecords, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(showRecords)
                .addGap(12, 12, 12))
        );

        CheckTotalAmount.setFont(new java.awt.Font("Times New Roman", 3, 16)); // NOI18N
        CheckTotalAmount.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CheckTotalAmount.setBorder(null);

        CheckTotalButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        CheckTotalButton.setText("Click to Check Total Amount");
        CheckTotalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckTotalButtonActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jLabel2.setText("Check Total Sells amount on Date");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel3.setText("Enter Date");

        TakeDate.setText("MM/DD/YYYY");
        TakeDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TakeDateActionPerformed(evt);
            }
        });

        DateSellAmount.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        DateSellAmount.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        DateSellAmount.setBorder(null);

        CheckAmountOndate.setText("Ok");
        CheckAmountOndate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckAmountOndateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(CheckTotalButton, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(CheckTotalAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(TakeDate, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(CheckAmountOndate)
                        .addGap(18, 18, 18)
                        .addComponent(DateSellAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(CheckTotalAmount)
                    .addComponent(CheckTotalButton, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CheckAmountOndate)
                    .addComponent(TakeDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DateSellAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TakeDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TakeDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TakeDateActionPerformed

    private void ShowDataAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_ShowDataAncestorAdded
        // TODO add your handling code here:
        
    }//GEN-LAST:event_ShowDataAncestorAdded

    private void showRecordsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showRecordsActionPerformed
        // TODO add your handling code here:
        try{
            Agro_Shop_Management obj = new Agro_Shop_Management();
            obj.Connection();
            DefaultTableModel model = (DefaultTableModel) ShowData.getModel();
            model.setRowCount(0);
            String sql ="select customerDetails.BillNo, CustomerName, p_date, totalAmount from CustomerDetails,Customerpurchase where CustomerDetails.BillNo = Customerpurchase.BillNo;";
            ResultSet rs = obj.st.executeQuery(sql);
            while(rs.next()){
                Object o[]={rs.getInt("BillNo"), rs.getString("customerName"),rs.getString("p_date"), rs.getFloat("totalAmount")};
                model.addRow(o);
            }
             obj.st.close();
             obj.con.close();
             obj=null;
        } catch(Exception e) {
         System.out.println("Exception 2: "+e);
            JOptionPane.showMessageDialog(null,"Exception in program plz contact developer");
        }
        
        
    }//GEN-LAST:event_showRecordsActionPerformed

    private void CheckTotalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckTotalButtonActionPerformed
        // TODO add your handling code here:
        try{
            Agro_Shop_Management obj = new Agro_Shop_Management();
            obj.Connection();
            String sql ="Select sum(totalAmount) from customerPurchase";
            ResultSet rs = obj.st.executeQuery(sql);
            double total = 0;
            while(rs.next()){
                total = rs.getFloat(1);
            }
            CheckTotalAmount.setText(""+total);
           obj.st.close();
             obj.con.close();
             obj=null; 
        } catch(Exception e){
            System.out.println("Exception 2: "+e);
            JOptionPane.showMessageDialog(null,"Exception in program plz contact developer");
        }
    }//GEN-LAST:event_CheckTotalButtonActionPerformed

    private void CheckAmountOndateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckAmountOndateActionPerformed
        // TODO add your handling code here:
        try{
            Agro_Shop_Management obj = new Agro_Shop_Management();
            obj.Connection();
            String date = TakeDate.getText();
            if(TakeDate.getText().equals("")){
                JOptionPane.showMessageDialog(null,"enter proper date");
            }
            String sql ="Select sum(totalAmount) from customerPurchase where p_date='"+date+"'";
            ResultSet rs = obj.st.executeQuery(sql);
            double total = 0;
            while(rs.next()){
                total = rs.getFloat(1);
            }
            DateSellAmount.setText(""+total);
            obj.st.close();
             obj.con.close();
             obj=null;
            
        } catch(HeadlessException | SQLException e){
            System.out.println("Exception 2: "+e);
            JOptionPane.showMessageDialog(null,"Exception in program plz contact developer");
        }
    }//GEN-LAST:event_CheckAmountOndateActionPerformed

    /**
     * @param args the command line arguments
     */
     

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CheckAmountOndate;
    private javax.swing.JTextField CheckTotalAmount;
    private javax.swing.JButton CheckTotalButton;
    private javax.swing.JTextField DateSellAmount;
    private javax.swing.JTable ShowData;
    private javax.swing.JTextField TakeDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton showRecords;
    // End of variables declaration//GEN-END:variables
}
